test:
  script:
  - apt-get update -qy
  - apt-get install -y python-dev python-pip
  - pip install -r requirements.txt

staging:
  type: deploy
  script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl
  - heroku config:set DEBUG_COLLECTSTATIC=1
  - dpl --provider=heroku --app=security-scorecard-online-stor --api-key=$HEROKU_STAGING_API_KEY
  only:
  - master
