ubuntu:latest
#
#staging:
#  type: deploy
#  script:
#  - apt-get update -qy
#  - apt-get install -y ruby-dev
#  - gem install dpl
#  - dpl --provider=heroku --app=security-scorecard-online-stor --api-key=$HEROKU_STAGING_API_KEY
#  only:
#  - master

test:
  script:
  - apt-get update && apt-get install --quiet --assume-yes python-dev python-pip unzip wget
  - pip install -U pip
  - wget --no-verbose https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - dpkg --install google-chrome-stable_current_amd64.deb; apt-get --fix-broken --assume-yes install
  - cp rf_test/requirements.txt /tmp/requirements.txt
  - pip install -r /tmp/requirements.txt
  - CHROMEDRIVER_VERSION=`wget --no-verbose --output-document - https://chromedriver.storage.googleapis.com/LATEST_RELEASE` && \
    wget --no-verbose --output-document /tmp/chromedriver_linux64.zip http://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip && \
    unzip -qq /tmp/chromedriver_linux64.zip -d /opt/chromedriver && \
    chmod +x /opt/chromedriver/chromedriver && \
    ln -fs /opt/chromedriver/chromedriver /usr/local/bin/chromedriver
  - ls
  - robot -v BROWSER:HeadlessChrome -d rf_test/test
  only:
    - master

